name: SSH-Compose
description: SSH into host and deploy repository with Docker-Compose
inputs:
  ssh_private_key:
    description: Private SSH key used for logging into remote system.
    required: true
  ssh_host:
    description: Remote host name.
    required: true
  ssh_port:
    description: Remote SSH port.
    default: 22
    required: true
  ssh_user:
    description: Remote user name.
    required: true
  docker_compose_prefix:
    description: Prefix for docker-compose containers. Must be unique for each repository if deploying to same remote.
    required: true
  docker_compose_filename:
    description: Docker compose file to use
    default: docker-compose.yaml
  no_cache:
    description: Builds docker file without cache
    default: false
  no_build:
    description: Only transfers the workplace
    default: false
runs:
  using: docker
  image: Dockerfile
  env:
    SSH_USER: ${{ inputs.ssh_user }}
    SSH_HOST: ${{ inputs.ssh_host }}
    SSH_PORT: ${{ inputs.ssh_port }}
    SSH_PRIVATE_KEY: ${{ inputs.ssh_private_key }}
    DOCKER_COMPOSE_FILENAME: ${{ inputs.docker_compose_filename }}
    DOCKER_COMPOSE_PREFIX: ${{ inputs.docker_compose_prefix }}
    NO_CACHE: ${{ inputs.no_cache }}
    NO_BUILD: ${{ inputs.no_build }}
